import "./style.css";
import lexington from "./scenes/lexington.json";
import declaration from "./scenes/declaration.json";
import delaware from "./scenes/delaware.json";
import { loadState } from "./engine/state";

/** Shell / chapter menu. Scenes light up as their assets land in
 *  /public/assets (generated by the pipeline scripts). Until then the two
 *  spikes are the playable surfaces. */

const scenes = [lexington, declaration, delaware];
const state = loadState();

const app = document.getElementById("app")!;
app.innerHTML = `
  <main style="max-width:680px;margin:8vh auto;padding:0 24px">
    <p style="color:var(--dim);letter-spacing:0.2em;text-transform:uppercase;font-size:12px">An interactive story</p>
    <h1 style="font-size:42px;font-weight:normal;margin:8px 0 4px">The Revolution</h1>
    <p style="color:var(--dim);margin-bottom:40px">1773 – 1783 · splats, world models, and ink</p>

    <h2 style="font-size:14px;color:var(--dim);text-transform:uppercase;letter-spacing:0.15em">Spikes (review builds)</h2>
    <ul style="list-style:none;padding:0;margin:12px 0 36px">
      <li style="margin:10px 0"><a href="/spikes/worldmodel/">Spike 1 — World model (Delaware boat, live Lingbot World 2 session)</a></li>
      <li style="margin:10px 0"><a href="/spikes/splat/">Spike 2 — Walkable splat (Lexington cue zones, Spark renderer)</a></li>
    </ul>

    <h2 style="font-size:14px;color:var(--dim);text-transform:uppercase;letter-spacing:0.15em">Chapters</h2>
    <ul style="list-style:none;padding:0;margin:12px 0">
      ${scenes
        .map(
          (s) => `
        <li style="margin:10px 0;color:var(--dim)">
          <span style="color:var(--ink)">${s.title}</span>
          — ${state.completedScenes.includes(s.id) ? "completed" : `<code>${s.renderer}</code> · awaiting assets`}
        </li>`
        )
        .join("")}
    </ul>
    <p style="color:var(--dim);font-size:13px;margin-top:36px">
      Generate assets with <code>npm run pipeline:worlds</code> /
      <code>pipeline:vo</code> / <code>pipeline:models</code>.
    </p>
  </main>
`;
