/** Authoritative visual evidence used to condition generated scene frames.
 * Paintings remain interpretations, not eyewitness cameras. `use` records the
 * limited production question each object may answer. */
export const visualSources = {
  "griffins-wharf.jpg": [{ title: "The Destruction of Tea at Boston Harbor", creator: "Sarony & Major", date: "1846", pageUrl: "https://www.loc.gov/pictures/item/2003664100/", imageUrl: "https://cdn.loc.gov/service/pnp/ds/03300/03379v.jpg", rights: "Library of Congress: no known restrictions on publication", use: "Shipboard labor, merchant-vessel silhouettes, and crowd scale only; reject its daylight and theatrical action." }],
  "teaparty-deck.jpg": [{ title: "The Destruction of Tea at Boston Harbor", creator: "Sarony & Major", date: "1846", pageUrl: "https://www.loc.gov/pictures/item/2003664100/", imageUrl: "https://cdn.loc.gov/service/pnp/ds/03300/03379v.jpg", rights: "Library of Congress: no known restrictions on publication", use: "Documented work-party tools and shipboard labor; do not reproduce its daylight, spectacle, or uniform disguises." }],
  "lexington.jpg": [{ title: "The Battle of Lexington, April 19, 1775", creator: "Amos Doolittle after Ralph Earl", date: "1775", pageUrl: "https://www.loc.gov/pictures/item/2015650276/", imageUrl: "https://cdn.loc.gov/service/pnp/ppmsca/39700/39753v.jpg", rights: "Library of Congress: no known restrictions on publication", use: "Near-contemporary site topography, meetinghouse, inn, road, and broad troop placement; not exact tactical geometry." }],
  "assembly-room.jpg": [{ title: "Restored Assembly Room, Independence Hall", creator: "U.S. National Park Service", date: "2015", pageUrl: "https://www.nps.gov/articles/000/assembly-room-furnishings.htm", imageUrl: "https://www.nps.gov/articles/000/images/Assembly-Room-960px.jpg?autorotate=false&format=webp&maxheight=1300&maxwidth=1300", rights: "U.S. National Park Service image; public-domain federal work", use: "Room proportions, surviving cockleshell frieze, platform, table layout, baize, and Windsor-chair material culture; seating remains conjectural." }],
  "delaware.jpg": [{ title: "Washington Crossing the Delaware", creator: "Emanuel Leutze", date: "1851", pageUrl: "https://www.metmuseum.org/art/collection/search/11417", imageUrl: "https://images.metmuseum.org/CRDImages/ad/web-large/DP215410.jpg", rights: "The Metropolitan Museum of Art Open Access; public domain", use: "The familiar mythic image to be contradicted: reject its daylight, flag, upright pose, small boat, and Rhine-like ice." }],
  "trenton.jpg": [{ title: "Sketch of the Engagement at Trenton", creator: "Andreas Wiederholdt", date: "1776", pageUrl: "https://www.loc.gov/item/gm71002184/", imageUrl: "https://tile.loc.gov/image-services/iiif/service:gmd:gmd381:g3814:g3814t:ar126700/full/pct:25/0/default.jpg", rights: "Library of Congress Geography and Map Division: free to use and reuse", use: "Eyewitness street network, approach routes, and unit relationship; it does not establish clothing, weather, or camera visibility." }],
  "saratoga-charge.jpg": [{ title: "Surrender of General Burgoyne", creator: "John Trumbull", date: "1821", pageUrl: "https://www.aoc.gov/explore-capitol-campus/art/surrender-general-burgoyne", imageUrl: "https://www.aoc.gov/sites/default/files/styles/popup_image/public/2026-01/Surrender_of_General_Burgoyne-2000w.jpg.webp?itok=EL8ypfof", rights: "Architect of the Capitol, federal collection", use: "Portrait-informed uniform variety, autumn terrain, and material palette only; not the charge, fortification geometry, or surrender choreography." }],
  "valley-forge.jpg": [{ title: "The March to Valley Forge", creator: "William B. T. Trego", date: "1883", pageUrl: "https://www.amrevmuseum.org/learn-and-explore/collection/breaking-down-trego-march", imageUrl: "https://moar-prod.imgix.net/87670f3a-e106-4497-8cc9-64d5c7c246c7/valley_forge_numbered_0.jpg?auto=compress%2Cformat&fit=min&fm=jpg&rect=37%2C0%2C1094%2C616", rights: "Historical painting used as research reference; do not redistribute the museum scan", use: "Material wear and human condition only; the later painting exaggerates snow and is not evidence for camp architecture." }],
  "yorktown-redoubt.jpg": [{ title: "Yorktown, 14 October 1781", creator: "H. Charles McBarron", date: "1972", pageUrl: "https://history.army.mil/Research/Artwork-and-Photography/Prints-and-Poster-Sets/Soldiers-of-the-American-Revolution-Print-Set/", imageUrl: "https://web.archive.org/web/20240629084017im_/https://history.army.mil/images/artphoto/pripos/revwar/Yrktn-t.png", rights: "U.S. Army Art Collection reference", use: "Researched earthen-and-log redoubt, abatis, unloaded muskets, bayonets, and uniform material; modern reconstruction, not eyewitness art." }],
  "surrender-field.jpg": [{ title: "Surrender of Lord Cornwallis", creator: "John Trumbull", date: "1819–1820", pageUrl: "https://www.aoc.gov/explore-capitol-campus/art/surrender-lord-cornwallis", imageUrl: "https://www.aoc.gov/sites/default/files/styles/popup_image/public/2026-01/Surrender_of_Lord_Cornwallis-2000w.jpg.webp?itok=XRzsNWvb", rights: "Architect of the Capitol, federal collection", use: "Life-portrait-informed officers, French and American line distinction, flags, and site palette; choreography is commemorative compression." }],
  "treaty-paris.jpg": [{ title: "American Commissioners of the Preliminary Peace Negotiations with Great Britain", creator: "Benjamin West", date: "ca. 1783", pageUrl: "https://www.loc.gov/pictures/item/2003654712/", imageUrl: "https://cdn.loc.gov/service/pnp/cph/3b10000/3b17000/3b17900/3b17926r.jpg", rights: "Original painting is public domain; LOC reproduction rights status not evaluated—reference conditioning only", use: "The actual five sitters, their varying finish, table, and blank right field; it depicts preliminary negotiations, not the definitive treaty signing." }],
};

export const visualSourcesFor = (file) => visualSources[file] ?? [];
